### YAML case settings for Sod2D

test: 1.5

mesh: 
    file: jet.msh
    serialRefLevels: 0
    parallelRefLevels: 0
    adaptive: false

physics:
    type:   perfectGas
    gamma:  1.4

internalField:
    type:       constant
    rho:        1.205
    U:          [0,0,0]
    p:          101325

boundaryField:
    inlet:
        tag: 0
        type:   inlet
        rhoI:   2.188
        UI:     [-649.4,0,0]
        pI:     52120
    outlet:
        tag: 1
        type:   outlet
    walls:
        tag: 2
        type:   slip
#    walls2:
#        tag: 3
#        type:   slip
    

spatial:
    polyOrder:      1
    riemannSolver:  HLL
    limiter:
        type:       BJ
        indicator:  BJ

time:
    restart: false
    restartCycle:  100
    nSavedFrames: 10

    order:  2

    tEnd:   1e-9
    dt:     1e-10

    type:   dynamic
    CoMax:  0.1

postProcess:
    format:     vtk
    visSteps:   1
