### YAML case settings for Munday nozzle

mesh: 
    file: nozzleStructSmall.msh
    serialRefLevels: 0
    parallelRefLevels: 0
    
    adaptive: 0
    totalErrorFraction: 0.0             ### use purely local threshold
    maxElemError: 2e-4
    hysteresis: 0.1                     ### derefinement safety coefficient
    preferConformingRefinement: false
    nonConformingLimit: 1

physics:
    type:   perfectGas
    gamma:  1.4

internalField:
    type:       constant
    rho:        1.204
    U:          [0,0,0]
    p:          101325

boundaryField:
    inlet:
        tag: 1
        type:   subsonicInlet
        rhoI:   4.41
        U:      [0,0,0]
        pI:     463955

    inlet2:
        tag: 6
        type:   subsonicInlet
        rhoI:   4.41
        U:      [0,0,0]
        pI:     463955

    nozzle:
        tag: 2
        type:   slip
    nozzle2:
        tag: 7
        type:   slip
    wallV1:
        tag: 3
#        type:   slip
        type:   outlet
        p:      101325
    wallV2:
        tag: 8
        type:   outlet
        p:      101325
#        type:   slip
    wallH1:
        tag: 4
        type:   outlet
        p:      101325
    wallH2:
        tag: 9
        type:   outlet
        p:      101325
    outlet1:
        tag: 5
        type:   outlet
        rhoI:   1.204
        U:      [0,0,0]
        p:      101325
    outlet2:
        tag: 10
        type:   outlet
        rhoI:   1.204
        U:      [0,0,0]
        p:      101325

spatial:
    polyOrder:      1
    riemannSolver:  HLL
    limiter:
        type:       BJ
        indicator:  BJ

time:
    restart: 0
    restartCycle: 2000
    nSavedFrames: 1

    order:  2

    tEnd:   0.02
    dt:     1e-10

    type:   dynamic
    CoMax:  0.3

postProcess:
    format:     vtk
    visSteps:   500
    checkTotalEnergy: false
    writeIndicators: 1