### YAML case settings for Sod2D

test: 1.5

mesh: 
    file: sod2d.msh
    serialRefLevels: 0
    parallelRefLevels: 0

physics:
    type:   perfectGas
    gamma:  1.4

internalField:
    type:       constant
    rho:        1.0
    U:          [0,0,0]
    p:          0.718

boundaryField:
    inlet:
        tag: 0
        type:   slip
        rhoI:   1.0
        UI:     [0,0,0]
        pI:     0.718
    outlet:
        tag: 1
        type:   slip
    walls:
        tag: 2
        type:   slip
    walls2:
        tag: 3
        type:   slip

spatial:
    polyOrder:      1
    riemannSolver:  HLL
    limiter:
        type:       FinDiff
        indicator:  Everywhere

time:
    restart: false
    restartCycle:  100
    nSavedFrames: 10

    order:  2

    tEnd:   0.2
    dt:     0.001

    type:   constant # dynamic
    CoMax:  0.1

postProcess:
    format:     vtk
    visSteps:   5
