### YAML case settings for Sod2D

test: 1.5

mesh: 
    file: fs.msh
    serialRefLevels: 0
    parallelRefLevels: 0

physics:
    type:   perfectGas
    gamma:  1.4

internalField:
    type:       constant
    rho:        1.0
    U:          [3,0,0]
    p:          0.714285714286

boundaryField:
    inlet:
        tag: 0
        type:   inlet
        rhoI:   1.0
        UI:     [-3,0,0]
        pI:     0.714285714286
    outlet:
        tag: 1
        type:   outlet
    walls:
        tag: 2
        type:   slip
    walls2:
        tag: 3
        type:   slip
    

spatial:
    polyOrder:      1
    riemannSolver:  HLL
    limiter:
        type:       BJ
        indicator:  BJ

time:
    restart: false
    restartCycle:  100
    nSavedFrames: 10

    order:  2

    tEnd:   4.0
    dt:     1e-4

    type:   dynamic
    CoMax:  0.1

postProcess:
    format:     vtk
    visSteps:   500
