### YAML case settings for Munday nozzle

mesh: 
    file: nozzle.msh
    serialRefLevels: 0
    parallelRefLevels: 0
    
    adaptive: 0
    totalErrorFraction: 0.0             ### use purely local threshold
    maxElemError: 5e-4
    hysteresis: 0.5                     ### derefinement safety coefficient
    preferConformingRefinement: false
    nonConformingLimit: 1

physics:
    type:   perfectGas
    gamma:  1.4

internalField:
    type:       constant
    rho:        1.204
    U:          [0,0,0]
    p:          101325

boundaryField:
    inlet:
        type:   subsonicInletTotalPressure
        pTot:   463955
        TTot:   500

    nozzle:
        type:   slip

    left:
        type:   totalPressureFixedTemperatureOutlet
        pTot:   101325
        TFix:   293.15

    topBottom:
        type:   totalPressureFixedTemperatureOutlet
        pTot:   101325
        TFix:   293.15

    outlet:
        type:   totalPressureFixedTemperatureOutlet
        pTot:   101325
        TFix:   293.15

spatial:
    polyOrder:      1
    riemannSolver:  HLL
    limiter:
        type:       Multi
        indicator:  BJ

time:
    restart: 0
    restartCycle: 122000
    nSavedFrames: 1

    order:  3

    tEnd:   1e-1
    dt:     1e-10

    type:   dynamic
    CoMax:  0.2

postProcess:
    format:     vtk
    visSteps:   100
    checkTotalEnergy: false
    writeIndicators: 0