### YAML case settings for Munday nozzle

mesh: 
    file: nozzle.msh
    serialRefLevels: 0
    parallelRefLevels: 0
    
    adaptive: 0
    totalErrorFraction: 0.0             ### use purely local threshold
    maxElemError: 2e-4
    hysteresis: 0.1                     ### derefinement safety coefficient
    preferConformingRefinement: false
    nonConformingLimit: 1

physics:
    type:   perfectGas
    gamma:  1.4

internalField:
    type:       constant
    rho:        1.204
    U:          [0,0,0]
    p:          101325

boundaryField:
    inlet:
        tag: 1
        type:   subsonicInlet
        rhoI:   4.41
        UI:     [0,0,0]
        pI:     500000
    outlet:
        tag: 2
        type:   slip
    walls:
        tag: 3
        type:   slip
    walls2:
        tag: 4
        type:   outlet
    walls3:
        tag: 5
        type:   outlet

spatial:
    polyOrder:      1
    riemannSolver:  HLL
    limiter:
        type:       BJ
        indicator:  BJ

time:
    restart: 0
    restartCycle: 2000
    nSavedFrames: 1

    order:  2

    tEnd:   1e-1
    dt:     1e-10

    type:   dynamic
    CoMax:  0.3

postProcess:
    format:     vtk
    visSteps:   500
    checkTotalEnergy: false