### YAML case settings for Sod2D

mesh: 
    file: KG.msh
    serialRefLevels: 0
    parallelRefLevels: 0
    
    adaptive: 0
    totalErrorFraction: 0.0             ### use purely local threshold
    maxElemError: 5e-4
    hysteresis: 0.25                     ### derefinement safety coefficient
    preferConformingRefinement: false
    nonConformingLimit: 3               ### maximum level of hanging nodes

physics:
    type:   perfectGas
    gamma:  1.4

internalField:
    type:       planeBreakup
#    rho:    1.0
#    U:      [0,0,0]
#    p:      1.0
    origin:     [0,0,0]
    normal:     [0,1,0]
    left:
        rho:    1.0
        U:      [0,0,0]
        p:      1.0
    right:
        rho:    1.0
        U:      [1.0,0,0]
        p:      1.0

boundaryField:
    inlet:
        tag: 1
        type:   outlet
    outlet:
        tag: 2
        type:   outlet

spatial:
    polyOrder:      1
    riemannSolver:  HLLC
    limiter:
        type:       BJ
        indicator:  Everywhere

time:
    restart: false
    
    restartCycle:  100
    nSavedFrames: 2

    order:  2

    tEnd:   20
    dt:     0.0082

    type:   dynamic
    CoMax:  0.5

postProcess:
    format:     vtk
    visSteps:   50
    checkTotalEnergy: 1
    writeIndicators: 1
