### YAML case settings for ForwardStep

test: 1.5

mesh: 
    file: x4_extr2DplaneQGDFoam_meshtest_0/internal.vtu #Face_Plane.msh
    serialRefLevels: 0
    parallelRefLevels: 0
    
    adaptive: false
    totalErrorFraction: 0.0             ### use purely local threshold
    maxElemError: 10e-3
    hysteresis: 0.5                     ### derefinement safety coefficient
    preferConformingRefinement: false
    nonConformingLimit: 1               ### maximum level of hanging nodes

physics:
    type:   perfectGas
    gamma:  1.4

internalField:
    type:       constant
    rho:        1.176413
    U:          [577.2273,0,0]
    p:          101325

boundaryField:
    inlet:
        tag: 1
        type:   inlet
        rhoI:   1.176413
        UI:     [-577.2273,0,0]
        pI:     101325
    outlet:
        tag: 2
        type:   outlet
    walls:
        tag: 0
        type:   slip
    walls2:
        tag: 3
        type:   slip
    

spatial:
    polyOrder:      1
    riemannSolver:  HLL
    limiter:
        type:       BJ
        indicator:  BJ

time:
    restart: false
    restartCycle:  100
    nSavedFrames: 10

    order:  2

    tEnd:   4.0
    dt:     1e-4

    type:   dynamic
    CoMax:  0.1

postProcess:
    format:     vtk
    visSteps:   100