### YAML case settings for Munday nozzle

mesh: 
    file: smol.msh
    serialRefLevels: 0
    parallelRefLevels: 0
    
    adaptive: 0
    totalErrorFraction: 0.0             ### use purely local threshold
    maxElemError: 2e-4
    hysteresis: 0.1                     ### derefinement safety coefficient
    preferConformingRefinement: false
    nonConformingLimit: 1

physics:
    type:   perfectGas
    gamma:  1.4
    R:      287

internalField:
    type:       constant
    rho:        1.204
    U:          [0,0,0]
    p:          101325

boundaryField:
    inlet:
        type:   subsonicInletTotalPressure
        pTot:   354637.5
        TTot:   293.15

#    inlet_mirrored:
#        type:   subsonicInlet
#        rhoI:   4.41
#        UI:      [0,0,0]
#        pI:     463955

    nozzle:
        type:   slip

#    nozzle_mirrored:
#        type:   slip

    wall: 
        type:   totalPressureFixedTemperatureOutlet
        pTot:   101325
        TFix:   293.15

#    wall_mirrored:
#        type:   outlet
#        rhoI:   1.204
#        U:      [0,0,0]
#        pI:      101325

#    walls_added:
#        type:   slip
#        type:   outlet
#        rhoI:   1.204
#        U:      [0,0,0]
#        pI:      101325

    top:
#        type:   outlet
        type:   totalPressureFixedTemperatureOutlet
        pTot:   101325
        TFix:   293.15

#    top_mirrored:
#        type:   totalPressureOutlet
#        rhoI:   1.204
#        U:      [0,0,0]
#        pI:      101325

    outlet:
        type:   totalPressureFixedTemperatureOutlet
        pTot:   101325
        TFix:   293.15

#    outlet_mirrored:
#        type:   outlet
#        rhoI:   1.204
#        U:      [0,0,0]
#        pI:      101325

spatial:
    polyOrder:      1
    riemannSolver:  HLL
    limiter:
        type:       Multi
        indicator:  Nowhere
        linearize:      0  ### work in Multi
        haveLastHope:   1  ### work in Multi

time:
    restart: 0
    restartCycle: 2000
    nSavedFrames: 1

    order:  2

    tEnd:   0.2
    dt:     5e-7

    type:   dynamic
    CoMax:  0.2

postProcess:
    format:     vtk
    visSteps:   300
    checkTotalEnergy: 0
    writeIndicators: 1