### YAML case settings for pulse from Shengtai Li

mesh: 
    file: pulse.msh
    serialRefLevels: 0
    parallelRefLevels: 0

    adaptive: 0
    totalErrorFraction: 0.0             ### use purely local threshold
    maxElemError: 1e-3
    hysteresis: 0.25                     ### derefinement safety coefficient
    preferConformingRefinement: false
    nonConformingLimit: 1               ### maximum level of hanging nodes

physics:
    type:   perfectGas
    gamma:  1.4

internalField:
    type:       densityPulse
    origin:     [0,0,0]
    epsilon:    5
    rho:    1.0
    U:      [0.5,0.5,0]
    p:      1.0

boundaryField:
    bottom:
        tag:    1
        type:   charOutlet
        rhoI:   1.0
        UI:     [0.5,0.5,0]
        pI:     0.718
    right:
        tag:    2
        type:   charOutlet
        rhoI:   1.0
        UI:     [0.5,0.5,0]
        pI:     0.718
    top:
        tag:    3
        type:   charOutlet
        rhoI:   1.0
        UI:     [0.5,0.5,0]
        pI:     0.718
    left:
        tag:    4
        type:   charOutlet
        rhoI:   1.0
        UI:     [0.5,0.5,0]
        pI:     0.718
                                        

spatial:
    polyOrder:      1
    riemannSolver:  HLLC
    limiter:
        type:       FinDiff
        indicator:  Nowhere

time:
    restart: 0
    
    restartCycle:  0
    nSavedFrames: 10

    order:  2

    tEnd:   10
    dt:     0.0001

    type:   dynamic
    CoMax:  0.2

postProcess:
    format:     vtk
    visSteps:   1
    checkTotalEnergy: true
    writeIndicators: 1